env:
  - "DB=mysql"
  - "DB=postgresql"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake --trace fulcrum:setup db:setup"
rvm:
  - 2.1.2
script:
  - "bundle exec rake travis"
